### ISSUE TITLE
external DAC

### ISSUE THREAD

**Issue by creisey** [pisicaverde/yet-another-internet-radio-ESP32#1]
hi there

your build looks amazing!

i planed since a long time to implement my own radio.

does your code also works with the DAC 5102a?`

thx in advance

**Comment by pisicaverde** [comment]
Hi, this player is build around the VS mp3 decoder, which features an internal DAC.
If you decode the mp3 stream in ESP32 and then send it to 5102A, it may work, but i think it's overcomplicated.

This radio version is however overcomplicated, it freezes sometime or gets the config file corrupted; in the next weeks I'll post a stripped down version.
Regards :)
Ciprian
